# Generated by Django 3.0.1 on 2020-01-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.IntegerField(blank=True, null=True, verbose_name='secret code')),
                ('alive', models.BooleanField(default=True, verbose_name='alive')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='last active')),
                ('kills', models.IntegerField(default=0, verbose_name='eliminations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
