# Generated by Django 3.0.1 on 2020-01-22 14:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=5, unique=True, verbose_name='access code')),
                ('open_duration', models.IntegerField(default=24, verbose_name='open duration')),
                ('in_progress', models.BooleanField(default=False, verbose_name='in progress')),
                ('rules', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('max_players', models.IntegerField(default=50, verbose_name='max players')),
                ('target_assignment_time', models.DateTimeField(blank=True, null=True, verbose_name='target assignment time')),
                ('start_elimination_time', models.DateTimeField(blank=True, null=True, verbose_name='start elimination time')),
                ('force_ended', models.BooleanField(default=False, verbose_name='force ended')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('game_admin', 'Can view game statistics')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.IntegerField(blank=True, null=True, verbose_name='secret code')),
                ('alive', models.BooleanField(default=False, verbose_name='alive')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='last active')),
                ('kills', models.IntegerField(blank=True, default=0, null=True, verbose_name='eliminations')),
                ('manual_open', models.BooleanField(default=False, verbose_name='manual open')),
                ('death_message', models.TextField(default='Was eliminated.', max_length=300, verbose_name='death message')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Game')),
                ('target', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'secret_code')},
            },
        ),
    ]
