# Generated by Django 3.0.1 on 2020-01-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rules',
        ),
    ]
