# Generated by Django 3.0.1 on 2020-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_game_game_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='respawn_time',
            field=models.IntegerField(default=0, verbose_name='respawn time'),
        ),
    ]
