# Generated by Django 3.0.1 on 2020-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_game_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='open_duration',
            field=models.IntegerField(default=24, verbose_name='open duration'),
        ),
    ]
