# Generated by Django 3.0.1 on 2020-01-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('game_admin', 'Can view game statistics')]},
        ),
        migrations.AlterField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=False, verbose_name='alive'),
        ),
    ]
