# Generated by Django 3.0.1 on 2020-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_game_open_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=50, verbose_name='max players'),
        ),
    ]
