# Generated by Django 3.0.1 on 2020-01-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200114_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='death_message',
            field=models.TextField(default='Was eliminated.', max_length=300, verbose_name='death message'),
        ),
    ]
