# Generated by Django 3.0.1 on 2020-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_player_death_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules',
            field=models.TextField(default=None, max_length=1000, verbose_name='rules'),
        ),
    ]
