# Generated by Django 3.0.1 on 2020-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_game_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='rules'),
        ),
    ]
