# Generated by Django 3.0.1 on 2020-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_game_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(max_length=1000, verbose_name='rules'),
        ),
    ]
